version: "3"
services:
  png2mp4:
    tty: true
    stdin_open: true
    container_name: png2mp4
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "12000:22"
    volumes:
      - ./cmd:/root/p/cmd
    environment:
        TZ: "Asia/Seoul"
