version: "3"
services:
  png2png_agent:
    tty: true
    stdin_open: true
    container_name: png2png_agent
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    environment:
        TZ: "Asia/Seoul"
    devices:
      - "/dev/fuse"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined