version: "3"
services:
  png2mp4_agent:
    tty: true
    stdin_open: true
    container_name: png2mp4_agent
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "12000:22"
    volumes:
      - /a:/source
    environment:
        TZ: "Asia/Seoul"
