version: "3"
services:
  png2mp4_server:
    tty: true
    stdin_open: true
    container_name: png2mp4_server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
      - "12000:22"
    environment:
        TZ: "Asia/Seoul"
